version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
      N8N_CUSTOM_EXTENSIONS: /home/node/.n8n/custom
    volumes:
      - ./.n8n/custom:/home/node/.n8n/custom
    ports:
      - "5678:5678"
    links:
      - postgres

volumes:
  postgres_data:
